### ISSUE TITLE
DEVELOPMENT STEPS

### ISSUE THREAD

**Issue by JordyHers** [JordyHers/e_rdv_health#1]
> E -rdv ISSUES <

@MichaelOptimus LISTE DES TACHES RELATIVES A E - RDV  **E rdv** 🤝

>LARAVEL
- [x] ADD DATABASE
- [x] ADD CONTROLLERS
- [x] HANDLE MODELS
- [x] SET UP ROUTES

>FLUTTER
- [x] CREATE LOGIN AUTH UI (login-register)
- [ ] USER PROFILE PAGE
- [ ] HOME PAGE
- [ ] USER RESERVATION FORM

**(Check on the internet if plugin need version updates )**

**Comment by MichaelOptimus** [comment]
Salut Jordy la partie api est achevé tu vas pouvoir continuer les autres phases on attend que tu ajoutes joseph pour le next

**Comment by JordyHers** [comment]
Ok je viens de voir ton update. Je vais voir au plus vite.
